// Code generated by MockGen. DO NOT EDIT.
// Source: health.go
//
// Generated by this command:
//
//	mockgen -package mocks -source=health.go -destination=mocks/health_mock.go HealthRepository,CacheRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHealthRepository is a mock of HealthRepository interface.
type MockHealthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHealthRepositoryMockRecorder
	isgomock struct{}
}

// MockHealthRepositoryMockRecorder is the mock recorder for MockHealthRepository.
type MockHealthRepositoryMockRecorder struct {
	mock *MockHealthRepository
}

// NewMockHealthRepository creates a new mock instance.
func NewMockHealthRepository(ctrl *gomock.Controller) *MockHealthRepository {
	mock := &MockHealthRepository{ctrl: ctrl}
	mock.recorder = &MockHealthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthRepository) EXPECT() *MockHealthRepositoryMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockHealthRepository) CheckHealth(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockHealthRepositoryMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockHealthRepository)(nil).CheckHealth), ctx)
}

// MockHealthCacheRepository is a mock of HealthCacheRepository interface.
type MockHealthCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockHealthCacheRepositoryMockRecorder is the mock recorder for MockHealthCacheRepository.
type MockHealthCacheRepositoryMockRecorder struct {
	mock *MockHealthCacheRepository
}

// NewMockHealthCacheRepository creates a new mock instance.
func NewMockHealthCacheRepository(ctrl *gomock.Controller) *MockHealthCacheRepository {
	mock := &MockHealthCacheRepository{ctrl: ctrl}
	mock.recorder = &MockHealthCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCacheRepository) EXPECT() *MockHealthCacheRepositoryMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockHealthCacheRepository) CheckHealth(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockHealthCacheRepositoryMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockHealthCacheRepository)(nil).CheckHealth), ctx)
}
