// Code generated by MockGen. DO NOT EDIT.
// Source: token.go
//
// Generated by this command:
//
//	mockgen -package mocks -source=token.go -destination=mocks/token_mock.go TokenBlacklist
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenBlacklist is a mock of TokenBlacklist interface.
type MockTokenBlacklist struct {
	ctrl     *gomock.Controller
	recorder *MockTokenBlacklistMockRecorder
	isgomock struct{}
}

// MockTokenBlacklistMockRecorder is the mock recorder for MockTokenBlacklist.
type MockTokenBlacklistMockRecorder struct {
	mock *MockTokenBlacklist
}

// NewMockTokenBlacklist creates a new mock instance.
func NewMockTokenBlacklist(ctrl *gomock.Controller) *MockTokenBlacklist {
	mock := &MockTokenBlacklist{ctrl: ctrl}
	mock.recorder = &MockTokenBlacklistMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenBlacklist) EXPECT() *MockTokenBlacklistMockRecorder {
	return m.recorder
}

// Blacklist mocks base method.
func (m *MockTokenBlacklist) Blacklist(ctx context.Context, token string, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blacklist", ctx, token, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Blacklist indicates an expected call of Blacklist.
func (mr *MockTokenBlacklistMockRecorder) Blacklist(ctx, token, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blacklist", reflect.TypeOf((*MockTokenBlacklist)(nil).Blacklist), ctx, token, expiration)
}

// IsBlacklisted mocks base method.
func (m *MockTokenBlacklist) IsBlacklisted(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBlacklisted", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBlacklisted indicates an expected call of IsBlacklisted.
func (mr *MockTokenBlacklistMockRecorder) IsBlacklisted(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBlacklisted", reflect.TypeOf((*MockTokenBlacklist)(nil).IsBlacklisted), ctx, token)
}
